name: mono
description: "Finance App"

publish_to: "none"

version: 0.4.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.9
  intl: ^0.18.1
  json_annotation: ^4.8.1

  # Firebase Dependencies
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - shorebird.yaml

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
